In [1]:
!pip install category_encoders 
!pip install optuna 
import pandas as pd
import numpy as np
import random 
import re 
import os 
import warnings
warnings.filterwarnings("ignore")
import category_encoders as ce 

from sklearn.metrics import (    accuracy_score,    confusion_matrix,f1_score,precision_score, recall_score,roc_auc_score)
from sklearn.metrics import make_scorer
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold,cross_val_score, StratifiedShuffleSplit

from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import SMOTE , ADASYN

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import BaggingClassifier,RandomForestClassifier,ExtraTreesClassifier,GradientBoostingClassifier,HistGradientBoostingClassifier,AdaBoostClassifier
from sklearn.ensemble import VotingClassifier,StackingClassifier
from sklearn.neighbors import KNeighborsClassifier
from catboost import CatBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

import optuna
from optuna.samplers import TPESampler

from sklearn.base import BaseEstimator, TransformerMixin, ClassifierMixin, clone
from sklearn.preprocessing import FunctionTransformer, StandardScaler, LabelEncoder

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


In [2]:
pd.set_option('display.max_rows', 500)
def seed_everything(seed):
    random.seed(seed)
    os.environ['PYTHONHASHSEED'] = str(seed)
    np.random.seed(seed)

seed_everything(42)

In [3]:
nation_corp = {
    'Austria': ['LGEAG'],    'Czech Republic': ['LGECZ'],    'France': ['LGEFS'],    'Germany': ['LGEDG'],    'Greece': ['LGEHS'],    'Hungary': ['LGEMK'],    'Italy': ['LGEIS'],    'Netherlands': ['LGESC', 'LGEEH', 'LGEBN'],    'Poland': ['LGEWR', 'LGEPL', 'LGEMA'],    'Portugal': ['LGEPT','LGEBT'],
    'EUs': ['LGEEB'],    'Romania': ['LGERO'],    'Spain': ['LGEES'],    'Sweden': ['LGENO', 'LGESW'],    'United Kingdom': ['LGEUK'],      'Kazakhstan': ['LGEAK'],    'Russia': ['LGERM', 'LGERI', 'LGERA'],
    'Ukraine': ['LGEUR'],    'Latvia': ['LGELV','LGELA'],    'Algeria': ['LGEAS'],
    'Egypt': ['LGEEG'],    'Jordan': ['LGELF'],    'Kenya': ['LGESK','LGEEF'],    'Morocco': ['LGEMC'],
    'Saudi Arabia': ['LGESJ'],    'Iran':['LGEIR'],     'Israel':['LGEYK'],     'The Republic of South Africa': ['LGESA'],
    'Tunisia': ['LGETU'],    'U.A.E': ['LGEOT', 'LGEDF', 'LGEGF', 'LGEME', 'LGEAF'],    'Nigeria': ['LGEAO', 'LGENI'],
    'Turkey': ['LGETK', 'LGEAT'],    'Australia': ['LGEAP'],
    'China': ['LGEQA', 'LGETL', 'LGECH', 'LGEYT', 'LGETR', 'LGETA', 'LGESY', 'LGESH', 'LGEQH', 'LGEQD', 'LGEPN', 'LGEND', 'LGEKS', 'LGEHZ', 'LGEHN', 'LGEHK'],
    'India': ['LGEIL'],    'Indonesia': ['LGEIN'],    'Japan': ['LGEJP'],    'Malaysia': ['LGEML'],    'Philippines': ['LGEPH'],
    'Singapore': ['LGESL'],    'Taiwan': ['LGETT'],    'Korea' :['LGEKR'],    'Thailand': ['LGETH'],    'Vietnam': ['LGEVN','LGEVH'],
     'Canada': ['LGECI'],    'Mexico': ['LGERS', 'LGEMX', 'LGEMS', 'LGEMM'],    'United States': ['LGEMR', 'LGEUS', 'LGEMU', 'LGEAI'],
    'Argentina': ['LGEAG','LGEAR'],    'Brazil': ['LGEBR','LGESP'],    'Chile': ['LGECL'],    'Colombia': ['LGEVZ', 'LGECB'],
    'Panama': ['Guatemala', 'LGEPS'],    'Peru': ['LGEPR']}
continent_nation={
    'Europe':['EUs','Austria', 'Czech Republic' ,'France' ,'Germany', 'Greece' ,'Hungary', 'Italy', 'Netherlands' ,'Poland' ,'Portugal' ,'Romania', 'Spain' ,'Sweden','United Kingdom'], 
    'Russia and CIS':['Kazakhstan','Russia', 'Ukraine', 'Latvia'],     'Africa and MiddleEast': ['Israel','Iran','Algeria', 'Egypt', 'Jordan', 'Kenya', 'Morocco','Saudi Arabia','The Republic of South Africa','Tunisia', 'U.A.E', 'Nigeria', 'Turkey'], 
    'Asia':['Korea','Australia','China','India','Indonesia','Japan','Malaysia','Philippines','Singapore','Taiwan','Thailand','Vietnam'], 
    'NorthAmerica' : ['Canada','Mexico','United States'],    'SouthAmerica' :['Argentina','Brazil','Chile','Colombia','Panama','Peru']
    
}
hemisphere = {
    'Northern': ['EUs', 'Austria', 'Czech Republic', 'France', 'Germany', 'Greece', 'Hungary', 'Italy', 'Netherlands', 'Poland', 'Portugal', 'Romania', 'Spain', 'Sweden', 'United Kingdom', 'Kazakhstan', 'Russia', 'Ukraine', 'Latvia', 'Israel', 'Iran', 'Jordan', 'Morocco', 'Saudi Arabia', 'Tunisia', 'Turkey', 'Korea', 'China', 'Japan', 'Taiwan', 'Canada', 'United States', 'Mexico', 'Panama'],
    'Southern': ['Algeria', 'Egypt', 'Kenya', 'The Republic of South Africa', 'U.A.E', 'Nigeria', 'Australia', 'India', 'Indonesia', 'Malaysia', 'Philippines', 'Singapore', 'Thailand', 'Vietnam', 'Argentina', 'Brazil', 'Chile', 'Colombia', 'Peru']
}
mapping_dict = {
#     "Toi muon tim hieu thong tin ky thuat, gia ca cua sp de su dung": "Product Information",
#     "tôi cần tham khảo giá và giải pháp từ LG": "Quotation or Purchase Consultation",
#     "Vui lòng báo giá giúp mình sản phẩm đo thân nhiệt Xin cảm ơn": "Request for quotation or purchase",
#     "LED Signage": "Product Information",
#     "Standalone": "Product Information",
#     "for school": "Other",
#     "Not specified": "Other",
#     "Intégrateur historique du George V": "Other",
#     "Solicito apoyo para realizar cotizacion de los dispositivos que ofrecen en la solución One Quick:": "Quotation or Purchase Consultation",
#     "Pantallas Interactivas para Clinicas": "Product Information",
#     "Hotel TV products": "Product Information",
#     "VRF": "Product Information",
#     "Preciso de um monitor médico para radiografia convencional e tomogrtafia.": "Sales Inquiry",
    "others": "Other",
    "Others": "Other",
    "other_": "Other",
    "other": "Other",
    "Etc.": "ETC.",
#     "window facing product": "Product Information",
#     "Digital platform": "Product Information",
#     "(Select ID_Needs)": "Other",
#     "One Quick:Flex": "Product Information",
#     "AIO": "Product Information",
#     "Needs": "Other",
#     "Hospital TV": "Product Information",
#     "i want to know the details about it": "Product Information",
#     "EDUCATIONAL EQUIPMENTS": "Product Information",
#     "TV interactive": "Product Information",
#     "Hola me pueden cotizar 19 pantallas interactivas de 100 pulgadas entregadas en Guayaquil -Ecuador.": "Request for quotation or purchase",
#     "teach": "Other",
#     "Display Textbook and photos": "Usage or technical consultation",
#     "High inch 86 / 98 or 110": "Product Information",
#     "quotation_": "Request for quotation or purchase",
#     "display product": "Product Information",
#     "first Info and pricing": "Quotation or Purchase Consultation",
#     "estoy buscando para Ecuador este producto LG MAGNIT micro LED, para un cliente de 138 pulgadas, con envió marítimo.": "Sales Inquiry",
#     "Evento_SdelEstero": "Other",
#     "probeam precio": "Sales Inquiry",
#     "media inquiry": "Sales Inquiry",
#     "Video Wall": "Product Information",
}


In [4]:

# 데이터 생성 및 전처리 함수 
def get_datas():
    train = pd.read_csv("train.csv")
    test = pd.read_csv("submission.csv").drop(['id','is_converted'], axis =1) # 테스트 데이터(제출파일의 데이터)
    train['is_converted']=np.where(train['is_converted']==True,1,0)
    return train, test 


def delete_cols(data, cols):
    data = data.drop(columns=cols)
    return data

def log_transform(data,cols):
    for col in cols :
        data[col+'log']=np.log1p(data[col]) 
    return data 


def eda_expected_timeline(df):
    
    def timeline_label(time):
    
        time = str(time).lower().replace(' ','').replace('_','').replace('/','').replace(',','').replace('~','').replace('&','').replace('-','').replace('.','')
        
        if time == 'lessthan3months':
            result = 'less than 3 months'
        elif time == '3months6months':
            result = '3 months ~ 6 months'
        elif time == '6months9months':
            result = '6 months ~ 9 months'
        elif time == '9months1year':
            result = '9 months ~ 1 year'
        elif time == 'morethanayear':
            result = 'more than a year'
        else:
            result = 'aimers_0203'
            
        return result
    
    df['expected_timeline'] = df['expected_timeline'].apply(timeline_label)
    
    return df


# inquiry type 전처리하기 
def eda_inquiry_type(df):
    df['inquiry_type']= df['inquiry_type'].map(mapping_dict).fillna(train['inquiry_type'])
    df.loc[df['inquiry_type'].str.contains('Solicito apoyo para realizar', na=False), 'inquiry_type'] = 'Quotation or Purchase Consultation'
    df['inquiry_type'] = df['inquiry_type'].str.lower()
    replacement = {'/': ' ', '-':' ', '_':' '}
    df['inquiry_type'].replace(replacement, regex=True, inplace=True)
    return df

def eda_inquiry_type_customer_position(df):
# inquiry_type feature 전처리 
    # customer_position feature 전처리 
    df['inquiry_type'] = df['inquiry_type'].str.lower()
    df['customer_position'] = df['customer_position'].str.lower()
    
    # 특수문자를 대체 문자열 지정
    replacement = {'/': ' ', '-':' ', '_':' '}
    # replace() 함수를 사용하여 특수 문자 대체
    df['inquiry_type'].replace(replacement, regex=True, inplace=True)
    df['customer_position'].replace(replacement, regex=True, inplace=True)
    
    # value count의 값이 1개인 feature name extraction (해당 방식 토의) 
    inquiry_series = df['inquiry_type'].value_counts()
    customer_position_series = df['customer_position'].value_counts()
    inquiry_replace_feature = []
    customer_replace_feature = []

    for idx, feature in enumerate(inquiry_series.index):
        if inquiry_series[idx] == 1:
            inquiry_replace_feature.append(feature)

    for idx, feature in enumerate(customer_position_series.index):
        if customer_position_series[idx] == 1:
            customer_replace_feature.append(feature)

    # 총 39개의 데이터 Concat
    df['inquiry_type'] = df['inquiry_type'].apply(lambda x: 'aimers_0203' if x in inquiry_replace_feature else x)
    # 총 53개의 데이터 Concat 
    df['customer_position'] = df['customer_position'].apply(lambda x: 'aimers_0203' if x in customer_replace_feature else x)

    return df

#customer type 처리 
def customer_type(data):
    data['customer_type']=data['customer_type'].fillna('none') 
    return data

# total_area 변수로 통일
def eda_business_area(df):
    for col in ['business_area','business_subarea']:
        df[col] = df[col].str.lower()
        df[col] = df[col].str.replace(" ", "") 
        df[col] = df[col].str.replace(r'[^\w\s]', "") 
        df[col] = df[col].fillna('nan') 
    df['total_area'] = df['business_area'].astype(str) + df['business_subarea'].astype(str)
    return df 

# 새로운 국가명, 대륙 열을 만들기 
def get_nation_continent(df):
    nation_corp_reverse ={v:k for k , values in nation_corp.items() for v in values }
    df['nation']=df['response_corporate'].map(nation_corp_reverse)
    continent_nation_reverse ={v:k for k , values in continent_nation.items() for v in values }
    df['continent']=df['nation'].map(continent_nation_reverse)
#     df = df.drop('customer_country',axis=1) 
    return df 

#라벨 인코딩 
def label_encoding(series: pd.Series) -> pd.Series:
    my_dict = {}
    series = series.astype(str)
    for idx, value in enumerate(sorted(series.unique())):
        my_dict[value] = idx
    series = series.map(my_dict)
    return series

# com_reg_ver_win_rate 최빈값으로 채우기 
def com_reg_fill(train,test):
    train['com_reg_ver_win_rate'] = train['com_reg_ver_win_rate'].fillna(train['com_reg_ver_win_rate'].mode()[0])
    test['com_reg_ver_win_rate'] = test['com_reg_ver_win_rate'].fillna(train['com_reg_ver_win_rate'].mode()[0])
    return train,test

#****************************Feature Engineering*************************************#

def fe_1(train,test):
    # unit continent으로 엮어서 영업 전환율 살펴보기 -> 'unit_conti_mean'열 새로 생성
    # 대륙별로 어느 사업부에 영업 성공율이 높은 지 
    se=train.groupby(['business_unit','continent'])['is_converted'].agg(['mean'])
    se = se.rename(columns={'mean':'unit_conti_mean'})
    train =train.merge(se, on=['business_unit','continent'], how ='left')
    test =test.merge(se, on=['business_unit','continent'], how ='left')
    return train,test 

def fe_2(train,test):
    # 영업 당담자가 어느 정도로 다양한 회사(customer_idx)을 담당하고 있는 지 
    
#     count = train.groupby('lead_owner').size().reset_index(name='leadowner_cnt')     
#     train = train.merge(count, on='lead_owner', how='left')
#     train['leadowner_cnt']= np.log1p(train['leadowner_cnt'])
#     test = test.merge(count, on='lead_owner', how= 'left')
#     test['leadowner_cnt']=np.log1p(test['leadowner_cnt'])
    unique_count = train.groupby('lead_owner')['customer_idx'].nunique().reset_index(name='unique_cusidx_cnt')
    train = train.merge(unique_count, on='lead_owner', how='left')
    test = test.merge(unique_count,on ='lead_owner',how ='left')
    train['unique_cusidx_cnt']= np.log1p(train['unique_cusidx_cnt'])
    test['unique_cusidx_cnt']= np.log1p(test['unique_cusidx_cnt'])
    
    return train, test 

def fe_3(train,test):
    # 영업담당자와 사업부로 영업전환 성공률 살펴보기 -> 어느 사업부를 어느 담당자가 담당해야 성공율이 높나 확인 

    se = train.groupby(['lead_owner','business_unit'])['is_converted'].agg(['mean']).rename(columns={'mean': 'owner_unit_mean'})
    train = train.merge(se, on=['lead_owner','business_unit'], how='left')
    test = test.merge(se, on=['lead_owner','business_unit'],how='left')
    return train, test

def fe_4(train,test):
    # customer_idx가 대기업, 중소기업으로 분류되는 경우 1을 부여 
    se = train[train.groupby('customer_idx')['enterprise'].transform('nunique') > 1]
    multi_company=list(se['customer_idx'].unique())
    train['multi_company']=np.where(train['customer_idx'].isin(multi_company) ,1,0)
    test['multi_company']=np.where(test['customer_idx'].isin(multi_company) ,1,0)
    return train, test

def fe_5(train,test):
    # LG지점 , 사업부 , bantsubmit으로 영업 성공율 살펴보기 -> 너무 과적합됨으로 제외 
    se = train.groupby(['response_corporate','business_unit','bant_submit'])['is_converted'].agg(['mean']).rename(columns={'mean':'idx_unit_mean'})
    train=train.merge(se,on=['response_corporate','business_unit','bant_submit'], how ='left')
    test=test.merge(se,on=['response_corporate','business_unit','bant_submit'], how ='left')
    return train, test
def fe_6(train,test):
    # 영업사원, 사업부, bandsubmit 으로 영업 성공율 살펴보기 -> 과적합으로 제외 
    se = train.groupby(['lead_owner','business_unit','bant_submit'])['is_converted'].agg(['mean']).rename(columns={'mean':'idx_unit_mean'})
    train=train.merge(se,on=['lead_owner','business_unit','bant_submit'], how ='left')
    test =test.merge(se,on =['lead_owner','business_unit','bant_submit'], how ='left')
    return train, test


def fe_7(train,test):
    # bant submit 제곱하기 -> isconverted와 corr는 더 높지만 성능향상은 없음 
    train['bant_submit2']=train['bant_submit']*train['bant_submit']
    test['bant_submit2']=test['bant_submit']*test['bant_submit']
    return train, test


def fe_8(df):
    # 국가별로 북반구와 남반구 특성을 생성하기 
    hemisphere_reverse ={v:k for k , values in hemisphere.items() for v in values }
    df['hemisphere'] =df['nation'].map(hemisphere_reverse)
    return df 

def fe_9(train,test):
    # 대륙별,사업 분야별, 사업부로 영업 성공률 살피기 
    se=train.groupby(['business_area','business_unit','continent'])['is_converted'].agg(['mean'])
    se = se.rename(columns={'mean':'area_unit_conti_mean'})
    train =train.merge(se, on=['business_area','business_unit','continent'], how ='left')
    test =test.merge(se, on=['business_area','business_unit','continent'], how ='left')
    return train, test

def fe_10(train,test):
    #국가별, 고객의 직업에 따라서 영업 성공율 살펴보기 
    se =train.groupby(['nation','customer_job'])['is_converted'].agg(['mean']).rename(columns={'mean':'nat_job_mean'})
    
    train =train.merge(se, on =['nation','customer_job'], how = 'left')
    train['nat_job_mean']=train['nat_job_mean'].fillna(train['nat_job_mean'].mean())
    
    test =test.merge(se, on =['nation','customer_job'], how = 'left')
    test['nat_job_mean']=test['nat_job_mean'].fillna(train['nat_job_mean'].mean())
    return train,test 


def fe_12(train,test):
    train['com_product'] = train['product_category'].apply(lambda x: 1 if 'signage' in str(x) else 0)
    
    se= train.groupby(['customer_idx'])['com_product'].agg(['mean']).rename(columns={'mean':'com_prod_mean'})
    train = train.merge(se, on =['customer_idx'], how ='left')
    test = test.merge(se, on =['customer_idx'], how ='left')
    train= train.drop('com_product', axis= 1 )
    return train,test
    
def create_grouped_features(train, test, group, numeric_var):
    # 범주형 특성들에 대해서 다른 수치형 데이터의 중앙값, 최대, 합을 새로운 열로 추가하기 
    train = train.copy()
    test = test.copy()

    aggs = ['median', 'max', 'sum']

    for agg in aggs:
        # groupby 후 aggregation
        a1 = train.groupby([group])[numeric_var].agg(agg).to_dict()
        # 새로운 feature 생성
        train[numeric_var+'_'+group+'_'+agg] = train[group].map(a1)
        test[numeric_var+'_'+group+'_'+agg] = test[group].map(a1)
    return train, test

def do_scale(train,test, scale_cols) :
    for c in scale_cols:
        min_value = train[c].min()
        max_value = train[c].max()
        train[c+"_scaled"] = (train[c] - min_value) / (max_value - min_value)
        test[c+"_scaled"] = (test[c] - min_value) / (max_value - min_value)
    return train,test

In [5]:
groups = ['business_unit','customer_idx']
numeric_vars = ['historical_existing_cnt', 'lead_desc_length']
scale_cols = ['com_reg_ver_win_rate','historical_existing_cnt', 'lead_desc_length','ver_win_rate_x']

In [6]:

# data 갖고오기 
train,test= get_datas() 

# 스케일링 하기 
train,test =do_scale(train,test,scale_cols)

# 범주형 데이터에 대해 수치형 데이터 통계값 추가
for group in groups:
    for numeric_var in numeric_vars:
        train, test = create_grouped_features(train, test, group, numeric_var)
        
# 전처리, 로그변환 수행하기 
columns_to_log=['com_reg_ver_win_rate','lead_desc_length']
train,test= log_transform(train,columns_to_log ),log_transform(test,columns_to_log)
train,test =eda_business_area(train),eda_business_area(test)
train,test= get_nation_continent(train),get_nation_continent(test)
train,test=eda_expected_timeline(train) ,eda_expected_timeline(test)
train,test=customer_type(train) ,customer_type(test)
train,test=eda_inquiry_type(train) ,eda_inquiry_type(test)

# Feature Engineering 
train,test = fe_1(train,test)
train,test = fe_2(train,test)
train,test = fe_3(train,test)
train,test = fe_9(train,test)
train,test = fe_10(train,test)

# train,test = fe_12(train,test)

for col in ['customer_idx','customer_type']:
    train[col+'count'] =train[col].map(train[col].value_counts())
    test[col+'count'] =test[col].map(train[col].value_counts())




In [7]:
# country.1지우지말기 
columns_to_delete=['nation']
# columns_to_delete=[]
train,test =delete_cols(train, columns_to_delete), delete_cols(test,columns_to_delete)

cols = [     'customer_country',    "business_subarea",    "business_area",    "business_unit",    "customer_type",    "enterprise",    "customer_job",    "inquiry_type",    "product_category",    "product_subcategory",    "product_modelname",    "customer_position",
      'customer_country.1', "response_corporate",  
     "expected_timeline",
'nation','continent',
'total_area',
#         'idx_unit'
# 'hemisphere'`
      ]
label_columns =list(set(cols)-set(columns_to_delete))

from category_encoders import CatBoostEncoder
enc = CatBoostEncoder(cols=label_columns)
enc.fit(train[label_columns], train['is_converted'])  # 'target'은 실제 데이터의 타겟 변수 이름에 맞게 변경
# 인코딩 적용
train[label_columns] = enc.transform(train[label_columns])
test[label_columns] = enc.transform(test[label_columns])


In [8]:
train = train.fillna(0)
test = test.fillna(0)
x = train.drop('is_converted', axis=1)
y = train.is_converted

# 모델 생성, 평가

In [9]:
def dtc_skfold(zero_wei,one_wei,seed) :
     #Decisiontree에 대해서만 skfold 적용하는 함수 
    real_preds = []
    class_weight={0:zero_wei , 1:one_wei}
    model = DecisionTreeClassifier(random_state=seed ,class_weight =class_weight)
    Skfold = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)  
#     Skfold = StratifiedShuffleSplit(n_splits=10, random_state=42)  
    cv_precision_scores, cv_recall_scores, cv_confusion_matrices, cv_f1_scores, cv_roc_auc_scores, cv_TN = [],[],[],[],[],[]
    tt = []
    for train_index, test_index in Skfold.split(x, y):  
        x_train, x_test, y_train, y_test= x.iloc[train_index], x.iloc[test_index], y.iloc[train_index], y.iloc[test_index]
        
        model.fit(x_train, y_train)
        pred = model.predict(x_test)
        test_pred = model.predict(test)
        real_preds.append(test_pred)
        
        pred_proba = model.predict_proba(x_test)[:, 1]  
        
        f1 = np.round(f1_score(y_test, pred, average='binary'), 4)  
        precision = np.round(precision_score(y_test, pred, average='binary'), 4)  
        recall = np.round(recall_score(y_test, pred, average='binary'), 4)  
        conf_matrix = confusion_matrix(y_test, pred)  
        roc_auc = roc_auc_score(y_test, pred_proba)  
        
        TN = conf_matrix[1][1]  # TN 값 저장
        ttone = conf_matrix[0][0]
        cv_TN.append(TN)  # TN 값 저장
        tt.append(ttone)
        cv_f1_scores.append(f1)  
        cv_precision_scores.append(precision)  
        cv_recall_scores.append(recall)  
        cv_confusion_matrices.append(conf_matrix)  
        cv_roc_auc_scores.append(roc_auc)  
        
    average_conf_matrix = np.mean(np.array(cv_confusion_matrices), axis=0)
    print(f"> F1 Score: {np.mean(cv_f1_scores)}, 정밀도: {np.mean(cv_precision_scores)}, 재현율: {np.mean(cv_recall_scores)}, ROC-AUC: {np.mean(cv_roc_auc_scores)}")
    print('> 평균 검증 오차행렬: \n', average_conf_matrix)  
    
    return real_preds, np.mean(cv_f1_scores), np.mean(cv_roc_auc_scores), np.mean(cv_TN) ,np.mean(tt) # TN 평균 값 리턴

f1_avg,roc_avg,tt=0,0,0
avg_get_1 =0
for seed in [5,11,30,322,8940]:
    _,f1,roc,ones,tts =dtc_skfold(1,1,seed)
    f1_avg+= f1 
    roc_avg+= roc 
    avg_get_1+=ones
    tt+= tts 
print(f1_avg/5,roc_avg/5,avg_get_1/5, tt/5)

dtc_preds,_,_,_,_= dtc_skfold(1,1,3)

predicts_array = np.array(dtc_preds)

# axis=0를 기준으로 평균 계산
# average_preds = np.mean(predicts_array, axis=0)

# average_preds[0]
final_prediction = np.mean(predicts_array, axis=0)

final_prediction = np.where(final_prediction < 0.1, 0, 1)

count_0 = np.size(np.where(final_prediction == 0))
count_2 = np.size(np.where(final_prediction >0))
count_1 = np.size(np.where(final_prediction == 1))

# 각 값을 출력
print("Count of 0:", count_0)
print("Count of 1:", count_1)

> F1 Score: 0.8561800000000002, 정밀도: 0.8516600000000001, 재현율: 0.8610300000000001, ROC-AUC: 0.9247850010210653
> 평균 검증 오차행렬: 
 [[5372.    72.9]
 [  67.4  417.6]]
> F1 Score: 0.85609, 정밀도: 0.8534, 재현율: 0.85897, ROC-AUC: 0.9239806636960027
> 평균 검증 오차행렬: 
 [[5373.2   71.7]
 [  68.4  416.6]]
> F1 Score: 0.8550800000000001, 정밀도: 0.8526, 재현율: 0.8579500000000001, ROC-AUC: 0.923519967254127
> 평균 검증 오차행렬: 
 [[5372.7   72.2]
 [  68.9  416.1]]
> F1 Score: 0.85517, 정밀도: 0.8524499999999999, 재현율: 0.85815, ROC-AUC: 0.9237236606761131
> 평균 검증 오차행렬: 
 [[5372.7   72.2]
 [  68.8  416.2]]
> F1 Score: 0.85519, 정밀도: 0.85315, 재현율: 0.85753, ROC-AUC: 0.9231403292782095
> 평균 검증 오차행렬: 
 [[5373.1   71.8]
 [  69.1  415.9]]
0.8555420000000001 0.9238299243851035 416.48 5372.740000000001
> F1 Score: 0.85472, 정밀도: 0.85122, 재현율: 0.8585600000000001, ROC-AUC: 0.923549858133514
> 평균 검증 오차행렬: 
 [[5371.9   73. ]
 [  68.6  416.4]]
Count of 0: 3437
Count of 1: 1834


In [10]:
sub=pd.read_csv('submission.csv')
sub['is_converted']= final_prediction
sub.to_csv('submission.csv',index= False)
# sub.to_csv('sota2_fe910_idxtypecnt_idxunit_1944.csv',index= False)